config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :usergambles
  resources :coin_flips
  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'gamble' => 'static_pages#gamble'

  get 'about' => 'static_pages#about'

end

app/models/coin_flip.rb
class CoinFlip < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/usergamble.rb
class Usergamble < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coin_flips_controller.rb
class CoinFlipsController < ApplicationController
  before_action :set_coin_flip, only: [:show, :edit, :update, :destroy]

  # GET /coin_flips
  # GET /coin_flips.json
  def index
    @coin_flips = CoinFlip.all
  end

  # GET /coin_flips/1
  # GET /coin_flips/1.json
  def show
  end

  # GET /coin_flips/new
  def new
    @coin_flip = CoinFlip.new
  end

  # GET /coin_flips/1/edit
  def edit
  end

  # POST /coin_flips
  # POST /coin_flips.json
  def create
    @coin_flip = CoinFlip.new(coin_flip_params)

    respond_to do |format|
      if @coin_flip.save
        format.html { redirect_to @coin_flip, notice: 'Coin flip was successfully created.' }
        format.json { render :show, status: :created, location: @coin_flip }
      else
        format.html { render :new }
        format.json { render json: @coin_flip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coin_flips/1
  # PATCH/PUT /coin_flips/1.json
  def update
    respond_to do |format|
      if @coin_flip.update(coin_flip_params)
        format.html { redirect_to @coin_flip, notice: 'Coin flip was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin_flip }
      else
        format.html { render :edit }
        format.json { render json: @coin_flip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coin_flips/1
  # DELETE /coin_flips/1.json
  def destroy
    @coin_flip.destroy
    respond_to do |format|
      format.html { redirect_to coin_flips_url, notice: 'Coin flip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_coin_flip
      @coin_flip = CoinFlip.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_flip_params
      params.require(:coin_flip).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def gamble
  end

  

end

app/controllers/usergambles_controller.rb
class UsergamblesController < ApplicationController
  before_action :set_usergamble, only: [:show, :edit, :update, :destroy]

  # GET /usergambles
  # GET /usergambles.json
  def index
    @usergambles = Usergamble.all
  end

  # GET /usergambles/1
  # GET /usergambles/1.json
  def show
  end

  # GET /usergambles/new
  def new
    @usergamble = Usergamble.new
  end

  # GET /usergambles/1/edit
  def edit
  end

  # POST /usergambles
  # POST /usergambles.json
  def create
    @usergamble = Usergamble.new(usergamble_params)

    respond_to do |format|
      if @usergamble.save
        format.html { redirect_to @usergamble, notice: 'Usergamble was successfully created.' }
        format.json { render :show, status: :created, location: @usergamble }
      else
        format.html { render :new }
        format.json { render json: @usergamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usergambles/1
  # PATCH/PUT /usergambles/1.json
  def update
    respond_to do |format|
      if @usergamble.update(usergamble_params)
        format.html { redirect_to @usergamble, notice: 'Usergamble was successfully updated.' }
        format.json { render :show, status: :ok, location: @usergamble }
      else
        format.html { render :edit }
        format.json { render json: @usergamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usergambles/1
  # DELETE /usergambles/1.json
  def destroy
    @usergamble.destroy
    respond_to do |format|
      format.html { redirect_to usergambles_url, notice: 'Usergamble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usergamble
      @usergamble = Usergamble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usergamble_params
      params.require(:usergamble).permit(:part_no, :description, :qty, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coin_flips_helper.rb
module CoinFlipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/usergambles_helper.rb
module UsergamblesHelper
end

app/views/coin_flips/_flipcoin.html.erb
class Coin
	def self.flip
		flip = 1 + rand(2)
		if flip == 2
			then
			puts "Heads"
		else
			puts "Tails"
		end
	end
end

app/views/coin_flips/_form.html.erb
<%= form_for(@coin_flip) do |f| %>
  <% if @coin_flip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coin_flip.errors.count, "error") %> prohibited this coin_flip from being saved:</h2>

      <ul>
      <% @coin_flip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coin_flips/edit.html.erb
<h1>Editing Coin Flip</h1>

<%= render 'form' %>

<%= link_to 'Show', @coin_flip %> |
<%= link_to 'Back', coin_flips_path %>

app/views/coin_flips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coin Flips</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coin_flips.each do |coin_flip| %>
      <tr>
        <td><%= coin_flip.name %></td>
        <td><%= link_to 'Show', coin_flip %></td>
        <td><%= link_to 'Edit', edit_coin_flip_path(coin_flip) %></td>
        <td><%= link_to 'Destroy', coin_flip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin flip', new_coin_flip_path %>

app/views/coin_flips/new.html.erb
<h1>New Coin Flip</h1>

<%= render 'form' %>

<%= link_to 'Back', coin_flips_path %>

app/views/coin_flips/show.html.erb
<h1>Winner</h1>

<%= link_to 'Back', coin_flips_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %> </li>
      <li><%= link_to "Gamble", gamble_path %> </li>
      <li><%= link_to "Help", help_path %> </li>
      <li><%= link_to "About", about_path %> </li>
     </ul>
  </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Icrie</title>
  <title>CriezOverThis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation.html.erb' %>
	</div>
<%= yield %>
	<%= render 'layouts/footer.html.erb' %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/gamble.html.erb
<h1>StaticPages#gamble</h1>
<p>Find me in app/views/static_pages/gamble.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

 <div class="jumbotron">
  <h1>KILL ME PLEASE</h1>
  <p>END THE SUFFERING</p>
  <%= link_to "Coin Flips", coin_flips_path %>
  </p>
 </div>

app/views/usergambles/_form.html.erb
<%= form_for(@usergamble) do |f| %>
  <% if @usergamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usergamble.errors.count, "error") %> prohibited this usergamble from being saved:</h2>

      <ul>
      <% @usergamble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :part_no %><br>
    <%= f.text_field :part_no %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.text_field :qty %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usergambles/edit.html.erb
<h1>Editing Usergamble</h1>

<%= render 'form' %>

<%= link_to 'Show', @usergamble %> |
<%= link_to 'Back', usergambles_path %>

app/views/usergambles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usergambles</h1>

<table>
  <thead>
    <tr>
      <th>Part no</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usergambles.each do |usergamble| %>
      <tr>
        <td><%= usergamble.part_no %></td>
        <td><%= usergamble.description %></td>
        <td><%= usergamble.qty %></td>
        <td><%= usergamble.price %></td>
        <td><%= link_to 'Show', usergamble %></td>
        <td><%= link_to 'Edit', edit_usergamble_path(usergamble) %></td>
        <td><%= link_to 'Destroy', usergamble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usergamble', new_usergamble_path %>

app/views/usergambles/new.html.erb
<h1>New Usergamble</h1>

<%= render 'form' %>

<%= link_to 'Back', usergambles_path %>

app/views/usergambles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part no:</strong>
  <%= @usergamble.part_no %>
</p>

<p>
  <strong>Description:</strong>
  <%= @usergamble.description %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @usergamble.qty %>
</p>

<p>
  <strong>Price:</strong>
  <%= @usergamble.price %>
</p>

<%= link_to 'Edit', edit_usergamble_path(@usergamble) %> |
<%= link_to 'Back', usergambles_path %>